# AmbientSenseBench synthetic-data generation app.
#
# Build:  docker build -t ambientsensebench .
# Run:    docker run --rm -p 8765:8765 ambientsensebench
# Open:   http://127.0.0.1:8765
FROM python:3.11-slim

# Non-interactive, unbuffered logs.
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    ASB_HOST=0.0.0.0 \
    ASB_PORT=8765

WORKDIR /app

# Install the package (dependencies are declared in pyproject.toml).
COPY pyproject.toml README.md ./
COPY src ./src
RUN pip install --no-cache-dir .

# Datasets generated by the app are written here; mount a volume to persist them.
RUN mkdir -p /data
VOLUME ["/data"]

EXPOSE 8765

# Run as a non-root user.
RUN useradd --create-home --uid 10001 appuser && chown -R appuser /data
USER appuser

# ASB_HOST/ASB_PORT allow overriding the bind address at run time.
CMD ["sh", "-c", "ambientsensebench app --host \"$ASB_HOST\" --port \"$ASB_PORT\" --output /data"]
